trigger:
  branches:
    include:
    - main

pr:
  branches:
    include:
    - main

jobs:
- job: daalp4yPyP
  pool:
    
    maxParallel: 2
  strategy:
    matrix:
      ubuntu - python9:
        imageName: 'ubuntu-16.04'
        python.version: '3.9'
      ubuntu - python8:
        imageName: 'ubuntu-16.04'
        python.version: '3.8'
      mac - python9:
        imageName: 'macos-10.14'
        python.version: '3.9'
      windows - python9:
        imageName: 'vs2017-win2016'
        python.version: '3.9'

  steps:
  - script: python --version
    displayName: 'Check Python'
  - script:
      pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple daal4py
      pip install pytest pandas scikit-learn
    displayName: 'Install daal4py'
  - script:
      python -c "import daal4py"
      git clone https://github.com/IntelPython/daal4py.git
      cd daal4py
      python -m unittest discover -v -s tests -p test*.py
      pytest --pyargs daal4py/sklearn/
      python examples/run_examples.py
      python -m daal4py examples/sycl/sklearn_sycl.py
    displayName: 'Testing daal4py'
