trigger:
  branches:
    include:
    - main

pr:
  branches:
    include:
    - main

jobs:
- job: daalp4yPyP
  strategy:
    matrix:
      ubuntu - python39:
        imageName: 'ubuntu-20.04'
        python.version: '3.9'
        pythonpypi: 'cp39-cp39-manylinux1_x86_64'
      ubuntu - python38:
        imageName: 'ubuntu-20.04'
        python.version: '3.8'
        pythonpypi: 'cp38-cp38-manylinux1_x86_64'
      ubuntu - python37:
        imageName: 'ubuntu-20.04'
        python.version: '3.7'
        pythonpypi: 'cp37-cp37m-manylinux1_x86_64'
      ubuntu - python36:
        imageName: 'ubuntu-20.04'
        python.version: '3.6'
        pythonpypi: 'cp36-cp36m-manylinux1_x86_64'
  pool:
    vmImage: $(imageName)
  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python $(python.version)'
    inputs:
      versionSpec: '$(python.version)'
  - script: python --version
    displayName: 'Check Python'
  - script: |
      pip install daal4py-2021.1-$(pythonpypi).whl
      pip install pytest pandas scikit-learn
    displayName: 'Install daal4py'
  - script: |
      pip install pyyaml
      git clone https://github.com/IntelPython/daal4py.git
      cd daal4py
      git checkout PetrovKP-patch-5
      source .circleci/run_and_compare.sh $(Pipeline.Workspace)/daal4py $(Build.ArtifactStagingDirectory)/patched_pypi_pytest_logs.tar.bz2
    displayName: 'Scilit-learn testing'
  - script: |
      echo "python -c import daal4py"
      python -c "import daal4py"
      echo "git clone"
      git clone https://github.com/IntelPython/daal4py.git
      cd daal4py
      python -m unittest discover -v -s tests -p test*.py
      pytest --pyargs daal4py/sklearn/
      # Failed with sycl CPU
      # python examples/run_examples.py
      # python -m daal4py examples/sycl/sklearn_sycl.py
    displayName: 'Testing daal4py'

