trigger:
  branches:
    include:
    - main

pr:
  branches:
    include:
    - main

jobs:
- job: daalp4yPyP
  strategy:
    matrix:
      ubuntu - python39:
        imageName: 'ubuntu-latest'
        python.version: '3.9'
      ubuntu - python38:
        imageName: 'ubuntu-latest'
        python.version: '3.8'
      ubuntu - python37:
        imageName: 'ubuntu-latest'
        python.version: '3.7'
      ubuntu - python36:
        imageName: 'ubuntu-latest'
        python.version: '3.6'
      mac - python39:
        imageName: 'macos-latest'
        python.version: '3.9'
      mac - python38:
        imageName: 'macos-latest'
        python.version: '3.8'
      mac - python37:
        imageName: 'macos-latest'
        python.version: '3.7'
      mac - python36:
        imageName: 'macos-latest'
        python.version: '3.6'
      windows - python39:
        imageName: 'windows-latest'
        python.version: '3.9'
      windows - python38:
        imageName: 'windows-latest'
        python.version: '3.8'
      windows - python37:
        imageName: 'windows-latest'
        python.version: '3.7'
      windows - python36:
        imageName: 'windows-latest'
        python.version: '3.6'
  pool:
    vmImage: $(imageName)
  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python $(python.version)'
    inputs:
      versionSpec: '$(python.version)'
  - script: python --version
    displayName: 'Check Python'
  - script:
      pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple daal4py
      pip install pytest pandas scikit-learn
    displayName: 'Install daal4py'
  - script:
      python -c "import daal4py"
      git clone https://github.com/IntelPython/daal4py.git
      cd daal4py
      python -m unittest discover -v -s tests -p test*.py
      pytest --pyargs daal4py/sklearn/
      python examples/run_examples.py
      python -m daal4py examples/sycl/sklearn_sycl.py
    displayName: 'Testing daal4py'
