trigger:
  branches:
    include:
    - main

pr:
  branches:
    include:
    - main

jobs:
- job: daalp4yPyP
  strategy:
    matrix:
      mac - python39:
        imageName: 'macos-latest'
        python.version: '3.9'
        pythonpypi: 'cp39-cp39'
      mac - python38:
        imageName: 'macos-latest'
        python.version: '3.8'
        pythonpypi: 'cp38-cp38'
      mac - python37:
        imageName: 'macos-latest'
        python.version: '3.7'
        pythonpypi: 'cp37-cp37m'
      mac - python36:
        imageName: 'macos-latest'
        python.version: '3.6'
        pythonpypi: 'cp36-cp36m'
  pool:
    vmImage: $(imageName)
  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python $(python.version)'
    inputs:
      versionSpec: '$(python.version)'
  - script: python --version
    displayName: 'Check Python'
  - script: |
      pip install daal4py-2021.1-$(pythonpypi)-macosx_10_15_x86_64.whl
      pip install pytest pandas scikit-learn 
    displayName: 'Install daal4py'
  - script: |
      python -c "import daal4py"
      git clone https://github.com/IntelPython/daal4py.git
      cd daal4py
      python -m unittest discover -v -s tests -p test*.py
      pytest --pyargs daal4py/sklearn/
      python examples/run_examples.py
      python -m daal4py examples/sycl/sklearn_sycl.py
    displayName: 'Testing daal4py'
