trigger:
  branches:
    include:
    - main

pr:
  branches:
    include:
    - main

jobs:
- job: daalp4yPyP
  strategy:
    matrix:
      ubuntu - python39:
        imageName: 'ubuntu-20.04'
        python.version: '3.9'
        pythonpypi: 'cp39-cp39-manylinux1_x86_64'
      ubuntu - python38:
        imageName: 'ubuntu-20.04'
        python.version: '3.8'
        pythonpypi: 'cp38-cp38-manylinux1_x86_64'
      ubuntu - python37:
        imageName: 'ubuntu-20.04'
        python.version: '3.7'
        pythonpypi: 'cp37-cp37m-manylinux1_x86_64'
      ubuntu - python36:
        imageName: 'ubuntu-20.04'
        python.version: '3.6'
        pythonpypi: 'cp36-cp36m-manylinux1_x86_64'
  pool:
    vmImage: $(imageName)
  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python $(python.version)'
    inputs:
      versionSpec: '$(python.version)'
  - script: |
      pip install daal4py-2021.1-$(pythonpypi).whl
      pip install pytest pandas scikit-learn
    displayName: 'Install daal4py'
  - script: |
      git clone https://github.com/IntelPython/daal4py.git
      cd daal4py
      git checkout PetrovKP-patch-5
    displayName: 'Clone of daal4py'
  - script: |
      wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
      sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
      rm GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
      echo "deb https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
      sudo add-apt-repository -y "deb https://apt.repos.intel.com/oneapi all main"
      sudo apt-get update
      cd daal4py
      mpirun -n 4 python -m unittest discover -v -s tests -p spmd*.py
    displayName: 'Testing of distributed daal4py'
  - script: |
      pip install pyyaml
      export DAAL4PY_ROOT=$(realpath daal4py)
      cd daal4py/.circleci
      export DESELECTED_TESTS=$(python deselect_tests.py ../deselected_tests.yaml --reduced)
      echo "-m daal4py -m pytest ${DESELECTED_TESTS} -q -ra --disable-warnings --pyargs sklearn"
      cd && ((python -m daal4py -m pytest ${DESELECTED_TESTS} -ra --disable-warnings --pyargs sklearn | tee ~/d4p.out) || true)
      export D4P=$(grep -E "=(\s\d*\w*,?)+ in .*\s=" ~/d4p.out)
      echo "Summary of patched run: " $D4P
      python ${DAAL4PY_ROOT}/.circleci/compare_runs.py
    displayName: 'Scilit-learn testing'
  - script: |
      echo "python -c import daal4py"
      python -c "import daal4py"
      cd daal4py
      python -m unittest discover -v -s tests -p test*.py
      pytest --pyargs daal4py/sklearn/
      # Failed with sycl CPU
      # python examples/run_examples.py
      # python -m daal4py examples/sycl/sklearn_sycl.py
    displayName: 'Testing of daal4py'

